FROM python:3.11

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install -r requirements.txt

COPY backend . 
COPY docker/backend/entrypoint.sh ./entrypoint.sh 

RUN chmod +x ./entrypoint.sh


CMD ["./entrypoint.sh"]

