services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/dockerfile
    ports:
      - "8000:8000"
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/dockerfile
    ports:
      - "5173:5173"
    command: npm run preview -- --host

